import React, { useState, useEffect, useRef } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import axios from 'axios';
import { toast } from 'sonner';
import {
  ArrowLeft, Save, Download, Upload, Bot, Send, Smartphone, 
  Monitor, Palette, Settings, Shield, Globe, ChevronRight
} from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../components/ui/tabs';
import { Switch } from '../components/ui/switch';

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

export default function AppBuilderPage() {
  const { appId } = useParams();
  const { axiosConfig } = useAuth();
  const navigate = useNavigate();
  const chatEndRef = useRef(null);

  const [app, setApp] = useState(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [chatMessages, setChatMessages] = useState([]);
  const [chatInput, setChatInput] = useState('');
  const [chatLoading, setChatLoading] = useState(false);
  const [activeTab, setActiveTab] = useState('config');

  useEffect(() => {
    fetchApp();
    fetchChat();
  }, [appId]); // eslint-disable-line

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages]);

  const fetchApp = async () => {
    try {
      const { data } = await axios.get(`${API}/apps/${appId}`, axiosConfig());
      setApp(data);
    } catch {
      toast.error('App not found');
      navigate('/dashboard');
    } finally {
      setLoading(false);
    }
  };

  const fetchChat = async () => {
    try {
      const { data } = await axios.get(`${API}/ai/chat/${appId}`, axiosConfig());
      setChatMessages(data);
    } catch {}
  };

  const saveApp = async () => {
    setSaving(true);
    try {
      const { data } = await axios.put(`${API}/apps/${appId}`, app, axiosConfig());
      setApp(data);
      toast.success('App saved');
    } catch {
      toast.error('Failed to save');
    } finally {
      setSaving(false);
    }
  };

  const generateApp = async () => {
    setGenerating(true);
    try {
      await axios.post(`${API}/apps/${appId}/generate`, {}, axiosConfig());
      await fetchApp();
      toast.success('App generated successfully!');
    } catch {
      toast.error('Generation failed');
    } finally {
      setGenerating(false);
    }
  };

  const sendChat = async (e) => {
    e.preventDefault();
    if (!chatInput.trim()) return;
    const msg = chatInput;
    setChatInput('');
    setChatMessages(prev => [...prev, { role: 'user', content: msg, created_at: new Date().toISOString() }]);
    setChatLoading(true);
    try {
      const { data } = await axios.post(`${API}/ai/chat`, { app_id: appId, message: msg }, axiosConfig());
      setChatMessages(prev => [...prev, { role: 'assistant', content: data.response, created_at: new Date().toISOString() }]);
    } catch (err) {
      const detail = err.response?.data?.detail || 'AI response failed';
      setChatMessages(prev => [...prev, { role: 'assistant', content: detail, created_at: new Date().toISOString() }]);
      toast.error(detail);
    } finally {
      setChatLoading(false);
    }
  };

  const updateField = (field, value) => {
    setApp(prev => ({ ...prev, [field]: value }));
  };

  const downloadConfig = () => {
    if (!app?.generation_result) {
      toast.error('Generate the app first');
      return;
    }
    const blob = new Blob([JSON.stringify(app.generation_result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${app.name.replace(/\s/g, '_')}_project.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadAndroidSource = () => {
    if (!app?.generation_result?.android) {
      toast.error('Generate the app first');
      return;
    }
    const content = `// ============================================
// ${app.name} - Android WebView Project
// Generated by Elyn Builder
// ============================================

// ====== build.gradle (app) ======
${app.generation_result.android.build_gradle}

// ====== MainActivity.kt ======
${app.generation_result.android.main_activity}

// ====== AndroidManifest.xml ======
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${app.package_name}">
    <uses-permission android:name="android.permission.INTERNET" />
    ${app.enable_geolocation ? '<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />' : ''}
    ${app.enable_camera ? '<uses-permission android:name="android.permission.CAMERA" />' : ''}
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="${app.name}"
        android:theme="@style/Theme.AppCompat.NoActionBar">
        <activity android:name=".MainActivity"
            android:exported="true"
            android:screenOrientation="${app.orientation}">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${app.name.replace(/\s/g, '_')}_android_source.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) return (
    <div className="min-h-screen flex items-center justify-center bg-[#FAFAFA]">
      <div className="w-8 h-8 border-2 border-[#002FA7] border-t-transparent rounded-full animate-spin" />
    </div>
  );

  if (!app) return null;

  return (
    <div className="min-h-screen bg-[#FAFAFA]" data-testid="app-builder-page">
      {/* Header */}
      <nav className="nav-glass sticky top-0 z-50 px-4 md:px-8" data-testid="builder-navbar">
        <div className="max-w-full flex items-center justify-between h-14">
          <div className="flex items-center gap-4">
            <Link to="/dashboard" className="text-[#52525B] hover:text-[#0A0A0A] transition-colors" data-testid="back-to-dashboard">
              <ArrowLeft className="w-5 h-5" />
            </Link>
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-sm flex items-center justify-center text-white font-heading font-bold text-xs" style={{ background: app.primary_color || '#002FA7' }}>
                {app.name?.charAt(0)?.toUpperCase()}
              </div>
              <span className="font-heading font-semibold text-[#0A0A0A] text-sm">{app.name}</span>
              <span className={`text-xs px-2 py-0.5 rounded-sm font-medium uppercase tracking-wider ${
                app.status === 'generated' ? 'bg-green-50 text-green-700 border border-green-200' : 'bg-zinc-100 text-zinc-500 border border-zinc-200'
              }`}>{app.status}</span>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={saveApp} disabled={saving} className="btn-secondary text-xs py-2 flex items-center gap-1.5" data-testid="save-btn">
              <Save className="w-3.5 h-3.5" /> {saving ? 'Saving...' : 'Save'}
            </button>
            <button onClick={generateApp} disabled={generating} className="btn-primary text-xs py-2 flex items-center gap-1.5" data-testid="generate-btn">
              <Smartphone className="w-3.5 h-3.5" /> {generating ? 'Generating...' : 'Generate'}
            </button>
          </div>
        </div>
      </nav>

      <div className="max-w-7xl mx-auto px-4 md:px-8 py-6">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <TabsList className="bg-white border border-[#E4E4E7] rounded-sm mb-6 p-1" data-testid="builder-tabs">
            <TabsTrigger value="config" className="rounded-sm text-xs data-[state=active]:bg-[#002FA7] data-[state=active]:text-white" data-testid="tab-config">
              <Settings className="w-3.5 h-3.5 mr-1.5" /> Configuration
            </TabsTrigger>
            <TabsTrigger value="design" className="rounded-sm text-xs data-[state=active]:bg-[#002FA7] data-[state=active]:text-white" data-testid="tab-design">
              <Palette className="w-3.5 h-3.5 mr-1.5" /> Design
            </TabsTrigger>
            <TabsTrigger value="ai" className="rounded-sm text-xs data-[state=active]:bg-[#002FA7] data-[state=active]:text-white" data-testid="tab-ai">
              <Bot className="w-3.5 h-3.5 mr-1.5" /> AI Assistant
            </TabsTrigger>
            <TabsTrigger value="publish" className="rounded-sm text-xs data-[state=active]:bg-[#002FA7] data-[state=active]:text-white" data-testid="tab-publish">
              <Upload className="w-3.5 h-3.5 mr-1.5" /> Publish
            </TabsTrigger>
          </TabsList>

          {/* CONFIG TAB */}
          <TabsContent value="config">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              <div className="lg:col-span-2 space-y-6">
                <div className="card-base p-6">
                  <h3 className="font-heading font-semibold text-[#0A0A0A] mb-4">Basic Settings</h3>
                  <div className="space-y-4">
                    <div>
                      <label className="label-text block mb-2">App Name</label>
                      <input value={app.name || ''} onChange={e => updateField('name', e.target.value)} className="input-base" data-testid="config-app-name" />
                    </div>
                    <div>
                      <label className="label-text block mb-2">Website URL</label>
                      <input value={app.url || ''} onChange={e => updateField('url', e.target.value)} className="input-base" data-testid="config-url" />
                    </div>
                    <div>
                      <label className="label-text block mb-2">Package Name</label>
                      <input value={app.package_name || ''} onChange={e => updateField('package_name', e.target.value)} className="input-base font-mono text-sm" data-testid="config-package-name" />
                    </div>
                    <div>
                      <label className="label-text block mb-2">Description</label>
                      <textarea value={app.description || ''} onChange={e => updateField('description', e.target.value)} className="input-base resize-none" rows={3} data-testid="config-description" />
                    </div>
                  </div>
                </div>
                <div className="card-base p-6">
                  <h3 className="font-heading font-semibold text-[#0A0A0A] mb-4">Permissions</h3>
                  <div className="space-y-4">
                    {[
                      { key: 'enable_javascript', label: 'JavaScript', desc: 'Enable JavaScript execution in WebView' },
                      { key: 'enable_geolocation', label: 'Geolocation', desc: 'Allow app to access device location' },
                      { key: 'enable_camera', label: 'Camera', desc: 'Allow app to access device camera' },
                      { key: 'enable_notifications', label: 'Push Notifications', desc: 'Enable push notifications' },
                    ].map(p => (
                      <div key={p.key} className="flex items-center justify-between py-2">
                        <div>
                          <div className="text-sm font-medium text-[#0A0A0A]">{p.label}</div>
                          <div className="text-xs text-[#A1A1AA]">{p.desc}</div>
                        </div>
                        <Switch checked={app[p.key] || false} onCheckedChange={v => updateField(p.key, v)} data-testid={`perm-${p.key}`} />
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Preview */}
              <div className="lg:col-span-1">
                <div className="card-base p-6 sticky top-20">
                  <h3 className="font-heading font-semibold text-[#0A0A0A] mb-4">Preview</h3>
                  <div className="mx-auto w-48 h-96 bg-[#0A0A0A] rounded-2xl border-4 border-[#18181B] overflow-hidden relative" data-testid="phone-preview">
                    {/* Status bar */}
                    <div className="h-6 flex items-center justify-center text-white text-[10px]" style={{ background: app.status_bar_color || '#002FA7' }}>
                      {app.name}
                    </div>
                    {/* WebView content */}
                    <div className="h-full bg-white flex flex-col items-center justify-center p-4">
                      <div className="w-12 h-12 rounded-lg flex items-center justify-center text-white font-heading font-bold text-lg mb-3" style={{ background: app.primary_color || '#002FA7' }}>
                        {app.name?.charAt(0)?.toUpperCase()}
                      </div>
                      <p className="text-xs text-center text-[#52525B] font-mono truncate w-full">{app.url}</p>
                      <div className="mt-4 w-full space-y-2">
                        <div className="h-2 bg-zinc-100 rounded-full w-full" />
                        <div className="h-2 bg-zinc-100 rounded-full w-4/5" />
                        <div className="h-2 bg-zinc-100 rounded-full w-3/5" />
                      </div>
                    </div>
                  </div>
                  <div className="mt-4 text-center">
                    <p className="text-xs text-[#A1A1AA]">Mobile App Preview</p>
                  </div>
                </div>
              </div>
            </div>
          </TabsContent>

          {/* DESIGN TAB */}
          <TabsContent value="design">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="card-base p-6">
                <h3 className="font-heading font-semibold text-[#0A0A0A] mb-4">Colors</h3>
                <div className="space-y-4">
                  {[
                    { key: 'primary_color', label: 'Primary Color' },
                    { key: 'splash_color', label: 'Splash Screen Color' },
                    { key: 'status_bar_color', label: 'Status Bar Color' },
                  ].map(c => (
                    <div key={c.key} className="flex items-center gap-3">
                      <input type="color" value={app[c.key] || '#002FA7'} onChange={e => updateField(c.key, e.target.value)} className="w-10 h-10 rounded-sm cursor-pointer border border-[#E4E4E7]" data-testid={`color-${c.key}`} />
                      <div>
                        <label className="text-sm font-medium text-[#0A0A0A]">{c.label}</label>
                        <div className="text-xs text-[#A1A1AA] font-mono">{app[c.key] || '#002FA7'}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
              <div className="card-base p-6">
                <h3 className="font-heading font-semibold text-[#0A0A0A] mb-4">Display Settings</h3>
                <div className="space-y-4">
                  <div>
                    <label className="label-text block mb-2">Orientation</label>
                    <select value={app.orientation || 'portrait'} onChange={e => updateField('orientation', e.target.value)} className="input-base" data-testid="orientation-select">
                      <option value="portrait">Portrait</option>
                      <option value="landscape">Landscape</option>
                      <option value="both">Both</option>
                    </select>
                  </div>
                  <div>
                    <label className="label-text block mb-2">App Icon URL</label>
                    <input value={app.app_icon_url || ''} onChange={e => updateField('app_icon_url', e.target.value)} className="input-base" placeholder="https://example.com/icon.png" data-testid="icon-url-input" />
                  </div>
                </div>
              </div>
            </div>
          </TabsContent>

          {/* AI TAB */}
          <TabsContent value="ai">
            <div className="card-base overflow-hidden" style={{ height: 'calc(100vh - 200px)' }}>
              <div className="flex flex-col h-full">
                <div className="p-4 border-b border-[#E4E4E7] flex items-center gap-2">
                  <Bot className="w-5 h-5 text-[#002FA7]" />
                  <h3 className="font-heading font-semibold text-[#0A0A0A]">Elyn AI Assistant</h3>
                  <span className="text-xs text-[#A1A1AA] ml-auto">Claude Sonnet 4.5</span>
                </div>
                <div className="flex-1 overflow-y-auto p-4 space-y-4" data-testid="chat-messages">
                  {chatMessages.length === 0 && (
                    <div className="text-center py-12">
                      <Bot className="w-10 h-10 text-[#A1A1AA] mx-auto mb-3" />
                      <p className="text-sm text-[#52525B] mb-1">AI Assistant is ready</p>
                      <p className="text-xs text-[#A1A1AA]">Ask me to help configure your app, generate descriptions, or optimize settings</p>
                    </div>
                  )}
                  {chatMessages.map((msg, i) => (
                    <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`} data-testid={`chat-msg-${i}`}>
                      <div className={`max-w-[80%] p-3 rounded-sm text-sm ${
                        msg.role === 'user' 
                          ? 'bg-[#002FA7] text-white' 
                          : 'bg-[#F4F4F5] text-[#0A0A0A] border border-[#E4E4E7]'
                      }`}>
                        <p className="whitespace-pre-wrap">{msg.content}</p>
                      </div>
                    </div>
                  ))}
                  {chatLoading && (
                    <div className="flex justify-start">
                      <div className="bg-[#F4F4F5] p-3 rounded-sm border border-[#E4E4E7]">
                        <div className="flex gap-1">
                          <div className="w-2 h-2 bg-[#A1A1AA] rounded-full animate-bounce" />
                          <div className="w-2 h-2 bg-[#A1A1AA] rounded-full animate-bounce" style={{ animationDelay: '0.1s' }} />
                          <div className="w-2 h-2 bg-[#A1A1AA] rounded-full animate-bounce" style={{ animationDelay: '0.2s' }} />
                        </div>
                      </div>
                    </div>
                  )}
                  <div ref={chatEndRef} />
                </div>
                <form onSubmit={sendChat} className="p-4 border-t border-[#E4E4E7] flex gap-2">
                  <input
                    value={chatInput}
                    onChange={e => setChatInput(e.target.value)}
                    className="input-base flex-1"
                    placeholder="Ask AI to help configure your app..."
                    disabled={chatLoading}
                    data-testid="chat-input"
                  />
                  <button type="submit" disabled={chatLoading || !chatInput.trim()} className="btn-primary px-4" data-testid="chat-send-btn">
                    <Send className="w-4 h-4" />
                  </button>
                </form>
              </div>
            </div>
          </TabsContent>

          {/* PUBLISH TAB */}
          <TabsContent value="publish">
            <div className="space-y-6">
              {/* Download Section */}
              <div className="card-base p-6">
                <h3 className="font-heading font-semibold text-[#0A0A0A] mb-2">Download Project</h3>
                <p className="text-sm text-[#52525B] mb-4">Download your generated app project files</p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <button onClick={downloadAndroidSource} className="btn-secondary flex items-center gap-3 py-4 justify-center" data-testid="download-android-btn">
                    <Smartphone className="w-5 h-5 text-green-600" />
                    <div className="text-left">
                      <div className="font-medium text-sm">Android Project</div>
                      <div className="text-xs text-[#A1A1AA]">Kotlin + WebView source</div>
                    </div>
                  </button>
                  <button onClick={downloadConfig} className="btn-secondary flex items-center gap-3 py-4 justify-center" data-testid="download-ios-btn">
                    <Monitor className="w-5 h-5 text-blue-600" />
                    <div className="text-left">
                      <div className="font-medium text-sm">iOS Project Config</div>
                      <div className="text-xs text-[#A1A1AA]">Swift + WKWebView config</div>
                    </div>
                  </button>
                </div>
                {app.status !== 'generated' && (
                  <p className="text-xs text-amber-600 mt-3 flex items-center gap-1">
                    <Shield className="w-3.5 h-3.5" /> Generate the app first before downloading
                  </p>
                )}
              </div>

              {/* Google Play Upload */}
              <div className="card-base p-6">
                <div className="flex items-center gap-2 mb-2">
                  <h3 className="font-heading font-semibold text-[#0A0A0A]">Google Play Upload</h3>
                  <span className="text-xs px-2 py-0.5 bg-[#002FA7] text-white rounded-sm font-medium">API</span>
                </div>
                <p className="text-sm text-[#52525B] mb-4">Configure your Google Play Console credentials for direct upload</p>
                <div className="space-y-4">
                  <div>
                    <label className="label-text block mb-2">App Title (Google Play)</label>
                    <input value={app.google_play_title || ''} onChange={e => updateField('google_play_title', e.target.value)} className="input-base" placeholder="App title on Google Play" data-testid="gplay-title" />
                  </div>
                  <div>
                    <label className="label-text block mb-2">Description (Google Play)</label>
                    <textarea value={app.google_play_description || ''} onChange={e => updateField('google_play_description', e.target.value)} className="input-base resize-none" rows={4} placeholder="App description for Google Play listing" data-testid="gplay-description" />
                  </div>
                  <div>
                    <label className="label-text block mb-2">Category</label>
                    <select value={app.google_play_category || ''} onChange={e => updateField('google_play_category', e.target.value)} className="input-base" data-testid="gplay-category">
                      <option value="">Select category</option>
                      <option value="business">Business</option>
                      <option value="education">Education</option>
                      <option value="entertainment">Entertainment</option>
                      <option value="finance">Finance</option>
                      <option value="food_drink">Food & Drink</option>
                      <option value="health_fitness">Health & Fitness</option>
                      <option value="lifestyle">Lifestyle</option>
                      <option value="news">News</option>
                      <option value="productivity">Productivity</option>
                      <option value="shopping">Shopping</option>
                      <option value="social">Social</option>
                      <option value="tools">Tools</option>
                      <option value="travel">Travel</option>
                    </select>
                  </div>
                  <div>
                    <label className="label-text block mb-2">Service Account Key (JSON)</label>
                    <textarea
                      value={app.google_play_service_account_key || ''}
                      onChange={e => updateField('google_play_service_account_key', e.target.value)}
                      className="input-base font-mono text-xs resize-none"
                      rows={4}
                      placeholder='Paste your Google Play Service Account JSON key here'
                      data-testid="gplay-service-key"
                    />
                    <p className="text-xs text-[#A1A1AA] mt-2">
                      Get this from Google Cloud Console → Service Accounts → Create Key → JSON
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <button onClick={saveApp} className="btn-primary text-sm flex items-center gap-1.5" data-testid="save-gplay-btn">
                      <Save className="w-3.5 h-3.5" /> Save Settings
                    </button>
                    <button
                      onClick={() => toast.info('Upload to Google Play requires a compiled APK. Generate and compile the project first.')}
                      className="btn-secondary text-sm flex items-center gap-1.5"
                      data-testid="upload-gplay-btn"
                    >
                      <Upload className="w-3.5 h-3.5" /> Upload to Google Play
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}
